version: '3'

services:
  database:
    image: mysql:latest
    restart: always
    container_name: database
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'blood_donation_schema'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
       test: "/usr/bin/mysql --user=user --password=password--execute \"SHOW DATABASES;\""
       interval: 2s
       timeout: 20s
       retries: 10

    networks:
     - backendNetwork
     
  springapi:
    image: milanviradia/backend:latest
    container_name: springapi
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/blood_donation_schema?createDatabaseIfNotExist=true&&allowPublicKeyRetrieval=true&&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password     
    ports:
      - 8087:8087
    depends_on:
      - database
    networks:
      - backendNetwork
      - frontendNetwork
    command: java -jar backend-0.0.1-SNAPSHOT.jar

  angular:
    image: milanviradia/frontend:latest
    container_name: angular
    ports: 
      - 4200:80
    depends_on:
      - springapi
    networks:
      - frontendNetwork
    

volumes:
  my-db:
  
networks:
  backendNetwork:
  frontendNetwork:
